### ISSUE TITLE
Tab capture restriction

### ISSUE THREAD

**Issue by aboba** [w3c/mediacapture-handle#43]
The Abstract says "It describes a mechanism for [tab capture](https://www.w3.org/TR/screen-capture/#dfn-browser) only."

However, Section 5.2 says: 

"If the track in question is not a video track, or is not the result of a capture of a display surface, then the user agent MUST return null."

This seems to allow a CaptureHandle to be returned in scenarios other than tab capture.

**Comment by eladalon1983** [comment]
Thanks for catching. PR up for review.
